

# This file was *autogenerated* from the file solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_257 = Integer(257)
from sage.all import *

f=open("invkey","r").read().split("\n")

N=_sage_const_8 
C = eval(f[_sage_const_0 ])
K = eval(f[_sage_const_1 ])

C = Matrix(Integers(_sage_const_257 ),C)
K = Matrix(Integers(_sage_const_257 ),K)

PT=K * BackslashOperator() * C
flag=''
for i in range(N):
	for j in range(N):
		flag+=chr(PT[i][j])

print(flag)

